#!/bin/sh
NAME="linux"
VERSION="5.15.79"
SOURCES="https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$VERSION.tar.xz;https://github.com/kreatoo/kernel-config/raw/main/.config"
SHA256SUM="cba39031dbc0eed0785b8afdc8c58cf23df83e47001b2354fa44486ae699c154  linux-5.15.79.tar.xz;efa978284bead4e7f77782643a467ade79a6b9793507f19294a8297d36735008  .config"
DESCRIPTION="Kreato's kernel"
prepare() {
    tar -xvf linux-$VERSION.tar.xz
    cd linux-$VERSION || exit 1
    cp ../.config .
}

build() {
    make -j$(nproc)
    make install
    make modules_install
}
